@startuml

state "Initialization" as I #LightBlue
state "Operational" as O #LightGreen
[*] --> I

I: entry/ Start
I: do/ Initialize variables

O: entry/ Start up Controller and LED
O: do/ Run Controller
O: exit/ Stop Controller and reset timers

I --> O: "o" command
O --> I: reset, "r" command

@enduml